#!/bin/sh -e

# Copyright (C) 2025, John Clark <inindev@gmail.com>

# kernel post-remove hook: /etc/kernel/postrm.d
# script to delete the specified dtb file from
# /boot after a kernel is package removed

version="$1"
dtb_files='<DTB_FILES>'

# passing the kernel version is required
if [ -z "${version}" ]; then
	echo >&2 "E: dtb_cp: ${DPKG_MAINTSCRIPT_PACKAGE:-kernel package} did not pass a version number"
	exit 2
fi

for dtb_file in ${dtb_files}; do
	target="/boot/${dtb_file}-${version}"
	echo "I: dtb_rm: removing ${target}"
	rm -f "${target}"
done

