#!/bin/sh -e

# Copyright (C) 2026, John Clark <inindev@gmail.com>

# kernel post-remove hook: /etc/kernel/postrm.d
# script to delete the dtb directory belonging to a
# kernel after it is package removed

version="$1"

# passing the kernel version is required
[ -z "$version" ] && { echo >&2 "E: dtb_rm: No version number provided"; exit 2; }

# /boot/dtbs/local is not owned by any kernel package and is never removed
echo "I: dtb_rm: removing /boot/dtbs/$version"
rm -rf "/boot/dtbs/$version"
