#!/bin/sh -e

# Copyright (C) 2025, John Clark <inindev@gmail.com>

# kernel post-install hook: /etc/kernel/postinst.d
# script to copy the specified dtb file to /boot
# after a new kernel is package installed

version="$1"
dtb_files='<DTB_FILES>'

# passing the kernel version is required
[ -z "$version" ] && { echo >&2 "E: dtb_cp: No version number provided"; exit 2; }

for dtb_file in $dtb_files; do
	source1="/boot/$dtb_file"
	source2="/usr/lib/linux-image-$version/rockchip/$dtb_file"
	target="/boot/$dtb_file-$version"

	if [ -f "$source2" ] && { [ ! -e "$source1" ] || [ "$(stat -c %s "$source2")" -gt "$(stat -c %s "$source1")" ]; }; then
		echo "I: dtb_cp: copying $source2 to $target"
		install -m 644 "$source2" "$target"
	elif [ -e "$source1" ]; then
		echo "I: dtb_cp: symlinking $source1 to $target"
		ln -sf "$(basename "$source1")" "$target"
	else
		res="$(find /usr/lib/linux-image* -name "$dtb_file" | sort -Vr | head -n1)"
		if [ -f "$res" ]; then
			echo "I: dtb_cp: copying $res to $target"
			install -m 644 "$res" "$target"
		else
			echo >&2 "E: dtb_cp: DTB file $dtb_file not found"
			exit 3
		fi
	fi
done

