#!/bin/sh -e

# Copyright (C) 2025, John Clark <inindev@gmail.com>

# kernel post-install hook: /etc/kernel/postinst.d script
# to set permissions after a new kernel is package installed

version="$1"
dtb_files='<DTB_FILES>'

# passing the kernel version is required
if [ -z "${version}" ]; then
        echo >&2 "E: kernel_chmod: ${DPKG_MAINTSCRIPT_PACKAGE:-kernel package} did not pass a version number"
        exit 2
fi

chmod 600 "/boot/System.map-${version}"
chmod 600 "/boot/vmlinuz-${version}"

for dtb_file in ${dtb_files}; do
	chmod 644 "/boot/${dtb_file}-${version}"
done

